/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author root
 */
public class TelaMensagens extends javax.swing.JFrame {

    /**
     * Creates new form TelaMensagens
     */
    public TelaMensagens() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   
    public void sucesso(int op){
        
        switch(op){
            case 1:
                JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso!");
              break;
            case 2:
                JOptionPane.showMessageDialog(null, "Cadastro atualizado com sucesso!");
                break;
            case 3:
                JOptionPane.showMessageDialog(null, "Exclusão efetuada com sucesso!");
        }
        
    }
    
    public void erro(int op){
        switch(op){
            case 1:
                JOptionPane.showMessageDialog(null, "Erro ao cadastrar", "Erro", JOptionPane.ERROR_MESSAGE);
                break;
            case 2:
                JOptionPane.showMessageDialog(null, "Erro ao buscar o cadastro", "Erro", JOptionPane.ERROR_MESSAGE);
                break;
            case 3:
                JOptionPane.showMessageDialog(null, "Erro ao atualizar o cadastro!", "Erro", JOptionPane.ERROR_MESSAGE);
                break;
            case 4:
                JOptionPane.showMessageDialog(null, "Erro ao excluir o cadastro!", "Erro", JOptionPane.ERROR_MESSAGE);
                break;
        }
    }
    public void erroBanco(Exception ex){
        JOptionPane.showMessageDialog(null, "Erro no Banco de Dados:"+ex.getMessage(), "Erro no banco", JOptionPane.ERROR_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
